module.exports = {
  AVAX: {
    pancake: require('./avax/pancake.json'),
    elk: require('./avax/elk.json'),
    joe: require('./avax/joe.json'),
    pangolin: require('./avax/pangolin.json'),
    sushi: require('./avax/sushi.json'),
    unifi: require('./avax/unifi.json'),
  },
  BSC: {
    ape: require('./bsc/ape.json'),
    bakery: require('./bsc/bakery.json'),
    elk: require('./bsc/elk.json'),
    empire: require('./bsc/empire.json'),
    jet: require('./bsc/jet.json'),
    kyber: require('./bsc/kyber.json'),
    pancake: require('./bsc/pancake.json'),
    panther: require('./bsc/panther.json'),
    sushi: require('./bsc/sushi.json'),
    unifi: require('./bsc/unifi.json'),
  },
  FANTOM: {
    dfyn: require('./fantom/dfyn.json'),
    elk: require('./fantom/elk.json'),
    empire: require('./fantom/empire.json'),
    hyper: require('./fantom/hyper.json'),
    jet: require('./fantom/jet.json'),
    kyber: require('./fantom/kyber.json'),
    sushi: require('./fantom/sushi.json'),
  },
  POLYGON: {
    dfyn: require('./polygon/dfyn.json'),
    elk: require('./polygon/elk.json'),
    empire: require('./polygon/empire.json'),
    jet: require('./polygon/jet.json'),
    kyber: require('./polygon/kyber.json'),
    sushi: require('./polygon/sushi.json'),
    unifi: require('./polygon/unifi.json'),
  },
};
